#!/bin/sh
killall conky
sleep 3s
conkdir=`realpath $0`
conkdir=${conkdir%/*}

conky -c $conkdir/gotham-clock.conkyrc &
conky -c $conkdir/lists.conf &
# conky -c $conkdir/xxx -d
# conky -c $conkdir/xxx -d
