syntax on
filetype indent plugin on
set nu
set modeline

" Enable folding
set foldmethod=indent
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za

set pastetoggle=<F9>

" Easier split control
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

vmap <leader>y :w! /tmp/vitmp<CR>
nmap <leader>p :r! cat /tmp/vitmp<CR>

set background=dark

set encoding=utf-8

" 4 spaces instead of hardtabs
set expandtab shiftwidth=4 softtabstop=4
